dev ✨ feat: set up formatter prettier

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,21 @@
-pnpm run lint
+set +e
+echo "🔍 Running ESLint..."
+eslint . 
+if [ $? -ne 0 ]; then
+  echo "❌ ESLint failed. Commit aborted."
+  exit 1
+fi
+
+echo "✅ Linting passed."
+
+prettier --write .
+if [ $? -ne 0 ]; then
+  echo "❌ Prettier formatting failed. Commit aborted."
+  exit 1
+fi
+
+
+echo "✅ Formatter passed."
+
+echo "✅ Linting and formatting passed. Proceeding with commit."
+exit 0
